//! Fixed-seed, text-free works: 20 choices per content unit, five units per chapter,
//! 95% local rejoin points, and 2.4 options per point. Compilation uses the public API.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;

use narrata_nodes::{
    Compilation, Error, NodeRegistry, ProjectManifest, ProjectSource, Result, compile,
    source::{GraphSource, PackageSource},
};
use serde_json::{Value, json};

pub const SEED: u64 = 0x4e41_5252_4154_4101;
pub const CHOICES_PER_UNIT: usize = 20;
pub const UNITS_PER_CHAPTER: usize = 5;

/// Only the sizes used by this experiment, bounded before any source allocation.
#[derive(Clone, Copy, Debug)]
pub struct WorkSize(usize);

impl WorkSize {
    pub fn new(choices: usize) -> Result<Self> {
        if !(100..=100_000).contains(&choices) || !choices.is_multiple_of(100) {
            return Err(Error::new(
                "benchmark",
                "choices",
                "expected a multiple of 100 in 100..=100000",
            ));
        }
        Ok(Self(choices))
    }

    pub fn choices(self) -> usize {
        self.0
    }
    pub fn units(self) -> usize {
        self.0 / CHOICES_PER_UNIT
    }
    pub fn chapters(self) -> usize {
        self.units() / UNITS_PER_CHAPTER
    }
    pub fn packages(self) -> usize {
        self.chapters().min(20) + 1
    }
}

fn schema(error: serde_json::Error) -> Error {
    Error::new("benchmark", "source", error.to_string())
}

struct Generator {
    next_node: u64,
    next_point: u64,
    next_option: u64,
}

impl Generator {
    fn id(kind: &str, counter: &mut u64) -> Value {
        *counter += 1;
        // Synthetic authored identities only: the seed and counter are stable, disjoint
        // within each authored kind, and never generated by the compiler.
        json!(format!("{kind}:{:016x}{:016x}", SEED, *counter))
    }

    fn node(&mut self, kind: &str, data: Value) -> Value {
        json!({"id": Self::id("node", &mut self.next_node), "type_id": format!("narrata.{kind}"), "data": data})
    }

    fn passage(&mut self, unit: usize, continuation: &str) -> Value {
        let key = format!("u{unit}");
        let mut points = Vec::new();
        for index in 0..CHOICES_PER_UNIT {
            let count = if (unit * CHOICES_PER_UNIT + index) % 5 < 2 {
                3
            } else {
                2
            };
            let mut options = Vec::new();
            for option in 0..count {
                let outcome = if index + 1 == CHOICES_PER_UNIT {
                    json!({"kind": "branch", "target": if option == 0 { continuation.to_owned() } else { format!("d{unit}") }})
                } else {
                    json!({"kind": "local", "reply": {"unit": {"provider": "synthetic", "key": &key}, "first": format!("r{index}-{option}"), "last": format!("r{index}-{option}")}, "rejoin": format!("b{}", index + 1)})
                };
                options.push(json!({
                    "id": Self::id("option", &mut self.next_option), "key": format!("o{option}"),
                    "label": {"provider": "synthetic", "key": format!("{key}.o{index}-{option}")},
                    "effects": [{"target": {"scope": "shared", "name": "score"}, "value": {"kind": "binary", "op": "add", "left": {"kind": "read", "scope": "shared", "name": "score"}, "right": {"kind": "literal", "value": option as i64 + 1}}}],
                    "outcome": outcome
                }));
            }
            points.push(json!({"id": Self::id("choice-point", &mut self.next_point), "key": format!("p{index}"), "placement": format!("b{index}"), "options": options}));
        }
        self.node("passage", json!({"body": {"unit": {"provider": "synthetic", "key": key}, "first": "b0", "last": "b20"}, "choice_points": points}))
    }

    fn units(&mut self, first: usize, end: usize, continuation: &str) -> BTreeMap<String, Value> {
        let mut nodes = BTreeMap::new();
        for unit in first..end {
            let next = if unit + 1 == end {
                continuation.to_owned()
            } else {
                format!("u{}", unit + 1)
            };
            nodes.insert(format!("u{unit}"), self.passage(unit, &next));
            // Alternate branch visits another passage of the same content unit; no new
            // choice or extra body unit. Graph changes happen through call/return.
            nodes.insert(format!("d{unit}"), self.node("passage", json!({"body": {"unit": {"provider": "synthetic", "key": format!("u{unit}")}, "first": "alternate", "last": "alternate"}, "next": next})));
        }
        nodes
    }

    fn graph(nodes: BTreeMap<String, Value>, entry: &str, imports: Value) -> Result<GraphSource> {
        serde_json::from_value(json!({"entry": entry, "outcomes": ["done"], "shared": {"score": "int"}, "imports": imports, "nodes": nodes})).map_err(schema)
    }
}

pub fn source(size: WorkSize) -> Result<ProjectSource> {
    let mut generator = Generator {
        next_node: 0,
        next_point: 0,
        next_option: 0,
    };
    let chapters = size.chapters();
    let groups = chapters.min(20);
    let mut packages = BTreeMap::new();
    let mut paths = BTreeMap::new();
    let mut bindings = Vec::new();
    let mut imports = BTreeMap::new();
    let mut root = generator.units(0, 1, "call0");
    for group in 0..groups {
        let package = format!("p{group:02}");
        paths.insert(package.clone(), format!("{package}.json"));
        imports.insert(format!("port{group}"), json!({"outcomes": ["done"]}));
        bindings.push(json!({"from": {"package": "root", "graph": "main", "port": format!("port{group}")}, "to": {"package": &package, "graph": "chapter-order"}}));
        root.insert(format!("call{group}"), generator.node("call", json!({"target": {"kind": "import", "port": format!("port{group}")}, "on_return": {"done": if group + 1 == groups { "out".to_owned() } else { format!("call{}", group + 1) }}})));
        let first = group * chapters / groups;
        let end = (group + 1) * chapters / groups;
        let mut graphs = BTreeMap::new();
        let mut order = BTreeMap::new();
        for chapter in first..end {
            let start_unit = (chapter * UNITS_PER_CHAPTER).max(1);
            let end_unit = (chapter + 1) * UNITS_PER_CHAPTER;
            let mut nodes = generator.units(start_unit, end_unit, "out");
            nodes.insert(
                "out".into(),
                generator.node("return", json!({"outcome": "done"})),
            );
            graphs.insert(
                format!("c{chapter:04}"),
                Generator::graph(nodes, &format!("u{start_unit}"), json!({}))?,
            );
            order.insert(format!("call{chapter}"), generator.node("call", json!({"target": {"kind": "local", "graph": format!("c{chapter:04}")}, "on_return": {"done": if chapter + 1 == end { "out".to_owned() } else { format!("call{}", chapter + 1) }}})));
        }
        order.insert(
            "out".into(),
            generator.node("return", json!({"outcome": "done"})),
        );
        graphs.insert(
            "chapter-order".into(),
            Generator::graph(order, &format!("call{first}"), json!({}))?,
        );
        packages.insert(
            package.clone(),
            PackageSource {
                id: format!("synthetic.{package}"),
                version: "1.0.0".into(),
                exports: vec!["chapter-order".into()],
                tombstones: vec![],
                graphs,
            },
        );
    }
    root.insert(
        "out".into(),
        generator.node("return", json!({"outcome": "done"})),
    );
    paths.insert("root".to_owned(), "root.json".to_owned());
    packages.insert(
        "root".into(),
        PackageSource {
            id: "synthetic.root".into(),
            version: "1.0.0".into(),
            exports: vec!["main".into()],
            tombstones: vec![],
            graphs: BTreeMap::from([(
                "main".into(),
                Generator::graph(root, "u0", serde_json::to_value(imports).map_err(schema)?)?,
            )]),
        },
    );
    let manifest: ProjectManifest = serde_json::from_value(json!({"format_version": narrata_nodes::FORMAT_VERSION, "product": {"id": "synthetic", "entry": {"package": "root", "graph": "main"}, "shared": {"score": 0}, "bindings": bindings}, "packages": paths})).map_err(schema)?;
    Ok(ProjectSource { manifest, packages })
}

pub fn generate(size: WorkSize) -> Result<Compilation> {
    compile(&source(size)?, &NodeRegistry::gamebook())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]
    use super::*;
    use narrata_nodes::{
        Pack, Program,
        plan::{Outcome, Plan},
    };

    #[test]
    fn fixed_seed_compiles_to_identical_checked_packs_with_the_requested_shape() {
        let size = WorkSize::new(1000).unwrap();
        let a = generate(size).unwrap();
        let b = generate(size).unwrap();
        assert_eq!(a.pack, b.pack);
        assert_eq!(a.lock, b.lock);
        let (program, _) = Program::from_pack(&a.pack).unwrap();
        program.verify_artifact().unwrap();
        let mut choices = 0;
        let mut local = 0;
        let mut options = 0;
        let mut units = std::collections::BTreeSet::new();
        let mut calls = 0;
        for key in program.manifest().graphs.keys() {
            let graph = program.graph(key).unwrap();
            for plan in graph.nodes.values() {
                if matches!(plan, Plan::Call { .. }) {
                    calls += 1;
                }
                if let Plan::Passage(passage) = plan {
                    if let Some(body) = &passage.body {
                        units.insert(body.unit.clone());
                    }
                    choices += passage.choice_points.len();
                    for point in &passage.choice_points {
                        options += point.options.len();
                        if point
                            .options
                            .iter()
                            .all(|o| matches!(o.outcome, Outcome::Local { .. }))
                        {
                            local += 1;
                        }
                    }
                }
            }
        }
        assert_eq!(
            (choices, local, options, units.len()),
            (1000, 950, 2400, 50)
        );
        assert_eq!(calls, 20);
        assert_eq!(program.manifest().graphs.len(), 21);
        assert_eq!(Pack::decode(&a.pack).unwrap().chunks.len(), 21);
        assert_eq!(program.manifest().packages.len(), size.packages());
    }

    #[test]
    fn sizes_are_checked_before_generation() {
        for invalid in [0, 1, 99, 101, 100001, usize::MAX] {
            assert!(WorkSize::new(invalid).is_err());
        }
        for valid in [100, 10000, 100000] {
            assert!(WorkSize::new(valid).is_ok());
        }
    }
}
